# Generated by Django 4.2.7 on 2023-11-23 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
                'db_table': 'Posicion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('flag_image', models.ImageField(upload_to='media')),
                ('emblem', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'Equipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('player_photo', models.ImageField(upload_to='media')),
                ('date_of_birth', models.DateField()),
                ('jersey_number', models.IntegerField()),
                ('is_starter', models.BooleanField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.team')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'Jugadores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('role', models.CharField(choices=[('Técnico', 'Técnico'), ('Asistente', 'Asistente'), ('Médico', 'Médico'), ('Preparador', 'Preparador')], help_text='Seleccione el rol', max_length=10)),
                ('nationality', models.CharField(choices=[('Colombia', 'Colombia'), ('Chile', 'Chile')], help_text='Seleccione la nacionalidad', max_length=255)),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.team')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'db_table': 'Tecnico',
                'ordering': ['id'],
            },
        ),
    ]
